---
permissions:
  contents: write
  pull-requests: write

name: Release Please

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          release-type: simple
          package-name: lze
